name: Auto Process Music Files

on:
  workflow_dispatch:
  push:
    branches:
      - music

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Run music processor
        env:
          WEBDAV_URL: ${{ secrets.WEBDAV_URL }}
          WEBDAV_UPLOAD_PATH: ${{ secrets.WEBDAV_UPLOAD_PATH }}
          WEBDAV_USER: ${{ secrets.WEBDAV_USER }}
          WEBDAV_PASS: ${{ secrets.WEBDAV_PASS }}
        run: |
          echo "WEBDAV_URL=${{ secrets.WEBDAV_URL }}"
          echo "WEBDAV_UPLOAD_PATH=${{ secrets.WEBDAV_UPLOAD_PATH }}"